### ISSUE TITLE
No module named '_mssql'

### ISSUE THREAD

**Issue by porlock** [StackStorm-Exchange/stackstorm-mssql#7]
Everything seems to be installed right, but integration dosen't work.. not sure where is the problem

```
root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# 
root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# ls
configs  exports  packs  persistent  st2  virtualenvs
root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# apt list freetds-dev
Listing... Done
freetds-dev/bionic-updates,bionic-security,now 1.00.82-2ubuntu0.1 amd64 [installed]
N: There is 1 additional version. Please use the '-a' switch to see it
root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# source ./
configs/     exports/     packs/       persistent/  st2/         virtualenvs/ 
root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# source ./virtualenvs/mssql/bin/activate
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# pip list packages
Package    Version
---------- -------
pip        20.3.3
pymssql    2.2.5
setuptools 51.3.3
six        1.16.0
wheel      0.36.2
WARNING: You are using pip version 20.3.3; however, version 21.3.1 is available.
You should consider upgrading via the '/opt/stackstorm/virtualenvs/mssql/bin/python -m pip install --upgrade pip' command.
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# wh
wheel      wheel3     wheel-3.6  wheel3.6   whereis    which      while      who        whoami     
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# which python
/opt/stackstorm/virtualenvs/mssql/bin/python
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# python ./packs/mssql/actions/
execute.insert.yaml           execute.non_query.yaml        execute.query_and_email.yaml  execute.query.yaml            execute.row.yaml              execute.scalar.yaml           lib/                          mssql_runner.py               workflows/                    
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# python ./packs/mssql/actions/lib/
__init__.py           mssql_action.py       results_processor.py  
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# python ./packs/mssql/actions/lib/mssql_action.py 
Traceback (most recent call last):
  File "./packs/mssql/actions/lib/mssql_action.py", line 2, in <module>
    import _mssql
ModuleNotFoundError: No module named '_mssql'
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# pythoin
bash: pythoin: command not found
(mssql) root@stackstorm-rnd-dev-st2actionrunner-85474d8b4d-ksmgs:/opt/stackstorm# python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql 
>>> import _mssql 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_mssql'

```

**Comment by sburlappp** [comment]
From pymssql's ChangeLog.rst:

Version 2.2.0
Convert pymssql to a package. Potential compatibility issue: projects using low level _mssql module need to import it from pymssql first.

Possible solutions:
 - Pin requirements to v2.1.5
 - Patch code to use "from pymssql import _mssql"
